In [14]:
!pip install scikit-learn -q

In [15]:
import os
import pandas as pd

from google.colab import drive

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_predict

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
PROJECT_FOLDER="/content/drive/MyDrive/CBR-PHI"

DATA_PATH=os.path.join(
    PROJECT_FOLDER,
    "data",
    "processed",
    "cases.csv"
)

df=pd.read_csv(DATA_PATH)

df.head()

,case_id,nomor_perkara,tahun,jenis_perkara,pemohon,termohon,amar_putusan,isi_putusan
0,1,k pdt sus phi g e n demi nkeadilan berdasarkan...,2022.0,Perselisihan Hubungan Industrial,NaN,an kasasi dan peninjauan kembali e menghukum t...,Ditolak,a i s e n o d n i k i l b u p e a r i s g e n ...
1,2,k pdt sus phi e n n demi keadilan berdasarkan ...,2021.0,Perselisihan Hubungan Industrial,NaN,l m b lisa marini warga negara indonesia dahul...,Ditolak,a i s e n o d n i k i l b u p e a r i s g e n ...
2,3,k pdt sus phi e n n demi keadilan berdasarkan ...,2021.0,Perselisihan Hubungan Industrial,NaN,ane banding ataupun kasasi a r a i s m ghalama...,Ditolak,a i s e n o d n i k i l b u p e a r i s g e n ...
3,4,k pdt sus phi g e n demi nkeadilan berdasarkan...,NaN,Perselisihan Hubungan Industrial,NaN,dengan saksama a diajukan dalam tenggang rwakt...,Ditolak,a i s e n o d n i k i l b u p e a r i s g e n ...
4,5,k pdt sus phi g e n n demi keadilan berdasarka...,2022.0,Perselisihan Hubungan Industrial,NaN,an atas putusan dalam p k perkara ini uitvoerb...,Dikabulkan,a i s e n o d n i k i l b u p e a r i s g e n ...

In [17]:
df["amar_putusan"].value_counts()

amar_putusan
Ditolak           22
Dikabulkan         4
Lainnya            3
Tidak Diterima     1
Name: count, dtype: int64

In [18]:
df["amar_putusan"] = df["amar_putusan"].replace({
    "Tidak Diterima": "Lainnya"
})

print(df["amar_putusan"].value_counts())

amar_putusan
Ditolak       22
Dikabulkan     4
Lainnya        4
Name: count, dtype: int64

In [19]:
X = df["isi_putusan"].fillna("")
y = df["amar_putusan"]

vectorizer = TfidfVectorizer(max_features=5000)

X_vector = vectorizer.fit_transform(X)

In [20]:
svm = SVC(
    kernel="linear",
    probability=True,
    random_state=42
)

In [21]:
cv = StratifiedKFold(
    n_splits=4,
    shuffle=True,
    random_state=42
)

prediction = cross_val_predict(
    svm,
    X_vector,
    y,
    cv=cv
)

print("Prediksi selesai")

Prediksi selesai

In [22]:
comparison = pd.DataFrame({
    "Actual": y,
    "Prediction": prediction
})

comparison.head()

       Actual Prediction
0     Ditolak    Ditolak
1     Ditolak    Ditolak
2     Ditolak    Ditolak
3     Ditolak    Ditolak
4  Dikabulkan    Ditolak

In [23]:
output = os.path.join(
    PROJECT_FOLDER,
    "data",
    "results",
    "prediction_results.csv"
)

comparison.to_csv(output, index=False)

print(output)

/content/drive/MyDrive/CBR-PHI/data/results/prediction_results.csv